### ISSUE TITLE
Upgrade to Java 17

### ISSUE THREAD

**Issue by azoitl** [eclipse/gef-classic#146] opened 2023-03-20 13:59 UTC
As announced by the Eclipse Platform team the Eclipse Platform will migrate to Java 17 with the upcoming 2023-06 release I would like to follow with GEF Classic rather soon. Therefore depending on the feedback of the community I would either do it as part of our 2023-06 (GEF Classic 3.16) or 2023-09 (GEF Classic 3.17) release. 

What is the opinion of the community on this?

\cc @pcdavid @Phillipus @Destrolaric @vogella

**Comment by Phillipus** [comment] 2023-03-20 14:06
Hi @azoitl,

does this simply mean changing these entries: `Bundle-RequiredExecutionEnvironment: JavaSE-17`? If so, is there any harm in leaving them at `JavaSE-11` in case GEF and Draw2d are being used outside of the Eclipse platform?

**Comment by azoitl** [comment] 2023-03-20 19:48
> Hi @azoitl,
> 
> does this simply mean changing these entries: `Bundle-RequiredExecutionEnvironment: JavaSE-17`? If so, is there any harm in leaving them at `JavaSE-11` in case GEF and Draw2d are being used outside of the Eclipse platform?

@Phillipus I was pretty sure about GEF but not about Draw2D and ZEST, therefore I checked. All three have dependencies to several Eclipse Platform plugins. While Draw2D only references eclipse.ui for the others it is a much deeper integration. So I don't see a use case for GEF Classic outside of  the Eclipse Platform. The only reason we could have is that we want GEF Classic 3.16 be also be used by non Eclipse 2023-06 users (e.g., Archi). For my main use-case of GEF Classic, 4diac  IDE, I have no concerns, I just submitted the Java 17 patches and we upgrade to latest Eclipse Platform every 3 months. 

On the other hand I guess I see it a bit like @vogella if we are on Simrel the Simrel versions should match and users can then decide which Eclipse Platform release with the according GEF Classic release they would like to use. As both is part of the same update site it makes their life easier.

**Comment by Phillipus** [comment] 2023-03-20 19:53
@azoitl Agreed on all your points. Archi is on Java 17 now anyway. :-)

**Comment by azoitl** [comment] 2023-03-20 20:07
@Phillipus I'm very happy to have you on board with a second RCP for feedback. I'm also looking so forward to Java 17. We where hold back by Xtext.

**Comment by Destrolaric** [comment] 2023-03-22 10:42
@azoitl If I understand correctly, some bundles of Eclipse will require Java 17 for their functionality. If this is the case, we will probably need to update DBeaver to Java 17(Which, unfortunately already been tried, and we reverted it due to several issues). We are not sure that we are currently able to upgrade to Java 17 before the 06 release.
We already use multiple eclipse bundles, so the GEF update will not be so influential. But migration for us will be a little bit delayed then.

**Comment by Destrolaric** [comment] 2023-03-22 12:44
@vogella is Mostly related to Kerberos and timezones. Also, there were mentions of driver issues after the update. They are problematic to debug because they require a specific environment to reproduce, so for a time, we reverted back to Java 11.

**Comment by azoitl** [comment] 2023-03-22 16:14
@Destrolaric you mean a link to the announcement of the Eclipse Platform. Sure: https://www.eclipse.org/lists/platform-dev/msg03746.html

If you look in there github repos you will already see the first issues and pull requests for managing the process.

**Comment by azoitl** [comment] 2023-03-27 08:22
@pcdavid To put it short: Yes it is!

Although I currently don't see a benefit on using Java 17 features at the API, I see great benefit in using it internally. In another project we just migrated and the instanceof pattern matching is a game changer. In GEF we can save hundreds if not even thousand lines of code.

For performance reasons I would see records for some features. However I currently don't see to get this backwards compatible therefore for me they are of the table. 

Currently I'm already testing all my changes with Eclipse 4diac and Eclipse GMF Runtime to ensure API stability. Eclipse Graphiti is on my todo list, but didn't yet manage to get it build on my machine. I'm also happy to test with Eclipse Sirius if the effort is reasonable.

Furthermore I brushed up my Java know how, and read the [Practical API Design](https://www.amazon.com/Jaroslav-Tulach/e/B003EZ2164/ref=dp_byline_cont_book_1) book by Jaroslav Tulach.

Since yesterday I have a strong case for my work on polishing GEF classic code: I found a severe discrepancy between documentation and implementation. Even two contradicting implementations. PR is on the way for this.

**Comment by azoitl** [comment] 2023-04-12 16:44
Just to let you all know also SWT will move to Java 17 with 2023-06: https://github.com/eclipse-platform/eclipse.platform.swt/discussions/623

So I will start migration in the next days, to have it for 3.16.0.M2 planned for 03.05.2023.

**Comment by azoitl** [comment] 2023-04-21 11:19
I just merged PR #183, with which GEF classic is migrated to Java 17.

**Comment by vogella** [comment] 2023-04-27 08:43
So close the issue?

**Closed as completed** 2023-05-25 06:37 UTC

**Comment by vogella** [comment] 2023-05-25 06:39
Thanks @azoitl
