### ISSUE TITLE
Duplicate Code Found "ZoomManager"

### ISSUE THREAD

**Issue by BauePhil** [eclipse/gef-classic#100] opened 2022-08-17 11:17 UTC
Very similar (almost identical) versions of the ZoomManager exist in [org.eclipse.gef](https://github.com/eclipse/gef-classic/blob/master/org.eclipse.gef/src/org/eclipse/gef/editparts/ZoomManager.java) and [org.eclipse.zest.core](https://github.com/eclipse/gef-classic/blob/master/org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/ZoomManager.java). Looks like the one in org.eclipse.zest.core is an ~~updated~~ older version.

**Comment by Phillipus** [comment] 2022-08-18 07:30
Is your idea to have just one version? If so, where? Both plug-ins exist separately. i.e. Zest can be used without GEF and vice-versa.

**Comment by BauePhil** [comment] 2022-08-18 07:53
Maybe draw2d as the Viewport it manipulates is draw2d? Not sure what causes more inconvenience though, keeping it as is or necessary refactoring after moving it. It just seems a little (code) smelly.

**Comment by Phillipus** [comment] 2022-08-18 08:06
I would be conservative in this kind of thing and leave it as is. It may be that a consumer has extended one of these classes or references it (we do quite some customisation in our use of GEF/Draw2d). Also, a package name change might break downstream.

**Comment by vogella** [comment] 2022-08-18 08:09
We could move it to a new place and extend the new class in the old ones and deprecate the old ones. Basically:

@Deprecated
ZoomManager(old) extends Zoommanager(new)

But if you do not think it is worth the effort, please close this ticket.

**Comment by Phillipus** [comment] 2022-08-18 08:20
@vogella Nice idea. There are quite a few references to `ZoomManager` in `org.eclipse.gef` which in my quick test of adding `@Deprecated` gave about 100 deprecation warnings elsewhere. My preference is to leave as is for now, but obviously I respect others' opinions.

**Comment by Phillipus** [comment] 2022-08-18 08:29
It gets complicated...

`ZoomManager` has a dependency on a `ZoomListener`. GEF has its own `ZoomListener` and so does Zest.

**Comment by BauePhil** [comment] 2022-08-18 08:37
Hmm well so even more duplicated code... Personally, I like the idea of @vogella but maybe wait and see what @azoitl has to say about it.

**Comment by Phillipus** [comment] 2022-08-18 08:42
In my quick test in our fork of GEF/Draw2d/Zest you'd have to take the best versions of `ZoomManager` and `ZoomListener` move them to `org.eclipse.draw2d` then extend these in the GEF and Zest versions. Also, add the `@Deprecated` annotation to the GEF and Zest versions and optionally suppress all the deprecation warnings in GEF/Zest. Downstream consumers might get a surprise with all the new deprecation warnings.

**Comment by Phillipus** [comment] 2022-08-18 08:52
And the strings need to be externalised. Each version has its own `SharedMessages` class. This will affect language packs.

**Comment by azoitl** [comment] 2022-08-18 13:19
I had already a quick look yesterday when I saw this report from @BauePhil. I noticed that the Zest ZoomManager is a classical copy modify class. Now we even have the state that both ZoomManager have fixes that would be nice in the other. That would  speak for a common class for both GEF and Zest. 

I also had an approach as proposed by @vogella in mind. But I understand the concerns from @Phillipus. I guess it would be a bad practice to perform the approach from @vogella but not mark the old classes deprecated?

Reducing the deprecation warnings would for me definitely be a high priority. We already have a lot of deprecation warnings. One place where we can easily can get rid of them is in the examples. Another option is to use where possible the new classes. Especially for the members and some internal code this should be possible. But I don't know if this is a good way to do.

Finally the ZoomManager in Zest is in an internal package. Does this give us more freedom for changes?

**Comment by Phillipus** [comment] 2022-08-18 13:25
Another difference between the two ZoomManagers is that the GEF version uses `java.text.DecimalFormat`
and `java.text.NumberFormat` and the Zest one does not. These were recently changed from the `com.ibm.icu` ones - https://github.com/eclipse/gef-classic/commit/6b6eba6093e4f62536bec7d2f198aa961765cfa9#diff-6aa7db396c6a47c8329cb8af87e196fd3d8054709e3008d7ad5953dfa4c4154d

**Comment by azoitl** [comment] 2022-08-18 13:30
> Another difference between the two ZoomManagers is that the GEF version uses `java.text.DecimalFormat` and `java.text.NumberFormat` and the Zest one does not. These were recently changed from the `com.ibm.icu` ones - [6b6eba6#diff-6aa7db396c6a47c8329cb8af87e196fd3d8054709e3008d7ad5953dfa4c4154d](https://github.com/eclipse/gef-classic/commit/6b6eba6093e4f62536bec7d2f198aa961765cfa9#diff-6aa7db396c6a47c8329cb8af87e196fd3d8054709e3008d7ad5953dfa4c4154d)

If I understand your comment here the GEF ZoomManager would be better am I right?

**Comment by Phillipus** [comment] 2022-08-18 13:35
> If I understand your comment here the GEF ZoomManager would be better am I right?

No. I think I prefer the Zoom one for that part.

> What I like on Zest's version is that for fit page, zoom all etc it would show the text in the menu combo box instead of the % value.

That might be an unexpected change for downstream users?

**Comment by azoitl** [comment] 2022-08-18 14:34
> > If I understand your comment here the GEF ZoomManager would be better am I right?
> 
> No. I think I prefer the Zoom one for that part.

Oh interesting didn't expect that. Is it because the DacimalFormat is an overkill here? Or because of reduced dependencies?

> > What I like on Zest's version is that for fit page, zoom all etc it would show the text in the menu combo box instead of the % value.
> 
> That might be an unexpected change for downstream users?

In the applications I develop it would be an improvement. Currently you select from the drop-down zoom all. And after the zoom has been performed you see some arbitrary number in the text field. I would find it more intuitive to show the zoom all message as feedback what zoom level I have. But maybe I'm the only one. Just checked with my pdf viewer and there it is like the current GEF so maybe it is good how it is.

**Comment by Phillipus** [comment] 2022-08-18 14:49
> Is it because the DacimalFormat is an overkill here? Or because of reduced dependencies?

Yes, both.

**Comment by Phillipus** [comment] 2022-08-18 14:56
> In the applications I develop it would be an improvement. Currently you select from the drop-down zoom all. And after the zoom has been performed you see some arbitrary number in the text field. I would find it more intuitive to show the zoom all message as feedback what zoom level I have. But maybe I'm the only one. Just checked with my pdf viewer and there it is like the current GEF so maybe it is good how it is.

I just tested using the Zest one in place of the GEF one. I'm not sure if I like to see a word or the percentage number. I'm so used to seeing the number. It may turn out to be one of those things that users either love or hate.

**Comment by Phillipus** [comment] 2022-08-21 18:53
Opened #106 so we can carry on there...

**Comment by azoitl** [comment] 2022-11-05 19:15
While working on a POC for Issue #124 I noticed that the duplication noted by @BauePhil should be fixed before. Somehow we deviated a bit in our discussion. By now I agree with @Phillipus that showing the zoom level as number also when zoom all or zoom page is called is the better solution. But then I think the better starting class would be the GEF version, or? Who wants to do perform the clean-up?

**Comment by azoitl** [comment] 2022-11-13 19:02
@Phillipus @BauePhil today I spent some time trying to move the ZoomManagers to draw2d. Most of the stuff went smooth. However I still do not have a solution for the SharedMessages. Any ideas what we could do with them?

**Comment by Phillipus** [comment] 2022-11-13 19:19
Can you reference the `SharedMessages` in the draw2d package?

**Comment by Phillipus** [comment] 2022-11-13 19:23
Perhaps Draw2D should get its own NLS String externalisation?

**Comment by azoitl** [comment] 2022-11-13 20:16
> Perhaps Draw2D should get its own NLS String externalisation? SharedMessages is rather an old way to do String externalisation.

Maybe. But this would in the end break any translations that are out there already. After letting it rest a bit I came up with a solution where the draw2d part wouldn't need the translatable messages. This also avoids that we have to mark the ZoomManager classes as deprecated. What do you think of it?

**Comment by Phillipus** [comment] 2022-11-14 09:10
> What do you think of it?

Genius. 💡 

The abstract ZoomManager solves the problems with having two instances each requiring their own label messages, and solves a few other issues. A great solution!

**Comment by azoitl** [comment] 2022-11-14 13:46
> > What do you think of it?
> 
> Genius. bulb
> 
> The abstract ZoomManager solves the problems with having two instances each requiring their own label messages, and solves a few other issues. A great solution!

Thx a lot. Happy that you like it. In the mean time I tested it with 4diac IDE. There we have a subclass of the ZoomManager and it worked like a charm. Unfortunately I'm still not able to compile GMF on my machine. But with the current solution I don't think we run into compatibility problems. But maybe @pcdavid if you have a minute to have a look it would be great!

**Comment by azoitl** [comment] 2022-11-22 17:03
As I  haven't heard anything bad I merged the PR today.

**Closed by azoitl** 2022-11-22 17:03 UTC

**Comment by Phillipus** [comment] 2022-11-22 17:19
Thanks for the work on this, Alois!

**Comment by pcdavid** [comment] 2023-01-02 16:13
Just FYI (not asking to revert anything!): the change in https://github.com/eclipse/gef-classic/commit/b2ea0dfddf207db417b9916263d4978ffb15dbfc has an unintended consequence. Just documenting it here as it surprised me and took a while to understand, so it may help others.

In Sirius we had a bundle which contained this code: `rootEditPart.getZoomManager().getZoom()`.

With GEF 3.14, this resolves to `org.eclipse.gef.editparts.ZoomManager#getZoom`, but in GEF 3.15 the method is now `org.eclipse.gef.editparts.ZoomManager#getZoom`.

The thing is, the bundle containing this code depended on GEF using `Import-Package` clauses (on `org.eclipse.draw2d`, `org.eclipse.draw2d.geometry`, `org.eclipse.draw2d.text`).
Building this unmodified code against GEF 3.15 I get:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.1:compile (default-compile) on project org.eclipse.sirius.ext.gmf.runtime: Compilation failure: Compilation failure: 
[ERROR] /home/pcdavid/work/sirius/git/org.eclipse.sirius/plugins/org.eclipse.sirius.ext.gmf.runtime/src/org/eclipse/sirius/ext/gmf/runtime/editparts/GraphicalHelper.java:[67] 
[ERROR]     scale = rootEditPart.getZoomManager().getZoom();
[ERROR]                                           ^^^^^^^
[ERROR] Access restriction: The method 'AbstractZoomManager.getZoom()' is not API (restriction on classpath entry '/home/pcdavid/tmp/repo/p2/osgi/bundle/org.eclipse.draw2d/3.12.0.202211301913/org.eclipse.draw2d-3.12.0.202211301913.jar')
```

As `getZoom` is now defined inside a package which we do not import.
Strangely, the issue is only at compile-time. At runtime everything works fine once the bundles are loaded/wired.

We can not just `Import-Package` the new `org.eclipse.draw2d.zoom` as this would fail with GEF 3.14 and earlier and we try to stay compatible. [The workaround](https://git.eclipse.org/c/sirius/org.eclipse.sirius.git/commit/?h=v7.0.x&id=b0b3b773f672a6aa5042739e1d7a0867167ce091) has been to move to a more coarse-grained `Require-Bundle`.

**Comment by azoitl** [comment] 2023-01-02 19:41
Thank you @pcdavid.  I would also not have expected that problem. But after your description it is rather logical. 

I created a new package as I thought the packages in draw2d are already rather overloaded. But with your feedback I will reconsider this in the future and stick more to the available packages.
