### ISSUE TITLE
Old GEF Classic releases have disappeared?

### ISSUE THREAD

**Issue by pcdavid** [eclipse/gef-classic#272] opened 2023-10-26 06:18 UTC
All the latest GMF Runtime nightly builds are red (https://ci.eclipse.org/gmf-runtime/job/gmf-runtime-all) with (for example for the 2021-09 target platform):

> [ERROR] Failed to resolve target definition file:/home/jenkins/agent/workspace/gmf-runtime-all/PLATFORM/2021-09/jdk/openjdk-jdk17-latest/label/migration/releng/org.eclipse.gmf.runtime.target/2021-09.target: Failed to load p2 metadata repository from location https://download.eclipse.org/tools/gef/classic/releases/3.14.0: No repository found at https://download.eclipse.org/tools/gef/classic/releases/3.14.0.

Indeed, https://download.eclipse.org/tools/gef/classic/releases/3.14.0 returns a 404.

https://download.eclipse.org/tools/gef/classic/releases/ now only contains `3.18.0M1` and `latest`.

**Comment by pcdavid** [comment] 2023-10-26 06:21
I hoped maybe they had simply been moved to https://archive.eclipse.org/tools/gef/classic/releases, but there's nothing there either.

**Comment by pcdavid** [comment] 2023-10-26 06:26
I see you've already reported https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3883

**Comment by azoitl** [comment] 2023-10-26 09:39
@pcdavid I'm sorry for the inconvenience. I'm not perfectly sure what caused the problem. But the reason for the problem is this failed build job: https://ci.eclipse.org/gef/job/promote-gef-classic/40/

My current assumption is that when the entered release name has not the correct format the safety removing of the release runs havoc. After some more reading I think this line is the problematic one: 
    `rm -rf /home/data/httpd/download.eclipse.org/tools/gef/classic/releases/${release}` 

Because is there the release name is based on special characters (e.g., coming from an html copy paste) results that the `rm -rf`command sees a `.` it would recursively remove all content in the directory.

I'm a bit rusted in shell script but googled a bit and found the following checks that I would add to our current build script:

```
if [${release} = '.' ] || [${release} = '.'. ] || [["${release}" =~ [!-.0-9a-z]*|[!0-9a-z] ]] then
  echo >&2 "Invalid release name"; exit 2; 
fi
```
In addition I would guard the `rm`command by:

```
if[-d ${release}] then
rm -rf /home/data/httpd/download.eclipse.org/tools/gef/classic/releases/${release}
fi
```

Do you think this is correct and sufficient?

However in addition as pointed out in the [help desk issue by Ed Merks](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3883#note_1265067) we would need an improved promotion release process. He gave xpect as an example. They use the following pom based approach: https://github.com/eclipse/Xpect/blob/master/org.eclipse.xpect.releng/promotion/pom.xml

Unfortunately this is way beyond my knowledge. Can anyone support us here?

**Comment by pcdavid** [comment] 2023-10-26 10:15
`if [-d ${release}] then` check that the "${release}" path denotes a directory. This will (almost) never be true for just `${release}`. This is not the path you try to remove so not the one to test.

Maybe something like this:

```sh
if [ -d "/home/data/httpd/download.eclipse.org/tools/gef/classic/releases/${release}" ]; then
    rm -rf "/home/data/httpd/download.eclipse.org/tools/gef/classic/releases/${release}"
fi
```

But this would not prevent invoking the `rm` with `release` being `.` (or worse, `../..`) and removing much more stuff than expected!

Anyway, https://www.shellcheck.net/ is your friend to identify common mistakes/traps in shell scripts.

**Comment by azoitl** [comment] 2023-10-26 10:23
Ah yes that is a good point. From what I understand the first if should handle the `.`, `..`, or cases with slashes in the name as it would only allow simple non slashed names for the release name.

**Comment by kysmith-csg** [comment] 2023-10-26 13:17
You could also look at what m2e does https://github.com/eclipse-m2e/m2e-core/blob/master/Jenkinsfile 

```bash
deployM2ERepository()
{
    echo Deploy m2e repo to ${1}
    ssh genie.m2e@projects-storage.eclipse.org "\
        rm -rf ${1}/* && \
        mkdir -p ${1}"
    scp -r org.eclipse.m2e.repository/target/repository/* genie.m2e@projects-storage.eclipse.org:${1}
}
# Read M2E branding version
version=$(xmllint --xpath 'string(/feature/@version)' org.eclipse.m2e.sdk.feature/feature.xml)
if [[ $version =~ ([0-9]+\\.[0-9]+\\.[0-9]+)\\.qualifier ]] # backslash itself has to be escaped in Jenkinsfile
then
    M2E_VERSION="${BASH_REMATCH[1]}"
else
    echo Failed to read M2E_VERSION. Abort deployment.
    exit 1
fi
deployM2ERepository /home/data/httpd/download.eclipse.org/technology/m2e/snapshots/${M2E_VERSION}
deployM2ERepository /home/data/httpd/download.eclipse.org/technology/m2e/snapshots/latest
```

Checking if the regex matches a m.n.p.q version with a capture group. Note that they don't first check if the directory exists, but this is fine because they are making sure it's a real version first and not something like `*` or `.`

**Comment by azoitl** [comment] 2023-10-26 15:29
@pcdavid & @kysmith-csg  thx for the feedback. Based on that I came up with the following deploy script:
```
sourcepath="/home/data/httpd/download.eclipse.org/tools/gef/classic/latest/*"
targetpath="/home/data/httpd/download.eclipse.org/tools/gef/classic/releases/"

deployGEFClassicRepository()
{
	echo Deploy GEF Classic repo to ${1}
	ssh genie.gef@projects-storage.eclipse.org "\
		rm -rf ${1}/* && \
		mkdir -p ${1} && \
		cp -r ${sourcepath} ${1}"
}

if [[ $1 =~ ([0-9]+\.[0-9]+\.[0-9RCM]+) ]]
then
	GEF_CLASSIC_VERSION="${BASH_REMATCH[1]}"	
else
	echo Wrong version format $1
	exit 1
fi

deployGEFClassicRepository ${targetpath}latest
deployGEFClassicRepository ${targetpath}${GEF_CLASSIC_VERSION}
```

This checks for correct version names and only forwards such for the deploy stage. I tested the regex here on my linux machine with different inputs. It definitly does not accept dangerous stuff and with such we will not loos releases anymore. 

If you think this is a good script I would use it in our jenkins build, and do some dry runs (i.e., comment the ssh part). If that succeeds as well I would use it for the next release (3.18.0M3).

**Comment by kysmith-csg** [comment] 2023-10-26 16:02
A few things:

1. Make sure this doesn't run unless you are doing a final release so the release artifact doesn't get wiped. I don't know how the GEF deployment actually works but I'm sure you already know how to use it.
2. It seems a bit weird to me to have a `/gef/classic/latest` and `/gef/classic/releases/latest`. I would think having this as a symlink (or composite p2 repo) pointing to the actual latest release would be best. Then we can keep `/gef/classic/latest` for nightly builds, and `/gef/classic/releases/latest` for the latest official release.

Otherwise this looks good.

---

Any update on restoring the old versions? I see the comment on gitlab that it is being restored from backup but so far nothing has appeared.

**Comment by azoitl** [comment] 2023-10-26 16:11
> A few things:
> 
>     1. Make sure this doesn't run unless you are doing a final release so the release artifact doesn't get wiped. I don't know how the GEF deployment actually works but I'm sure you already know how to use it.

Yes this is clear. The overall functionality didn't change. I just added safety nets so that my clumsiness can not again wipe out all releases.

> 
>     2. It seems a bit weird to me to have a `/gef/classic/latest` and `/gef/classic/releases/latest`. I would think having this as a symlink (or composite p2 repo) pointing to the actual latest release would be best. Then we can keep `/gef/classic/latest` for nightly builds, and `/gef/classic/releases/latest` for the latest official release.

That is an interesting point. In general the semantic between both directory is like that. But if I understand you correctly instead of copying twice I would create a symlink from latest to the release I just copied. So the ssh part changes to:

```
ssh genie.gef@projects-storage.eclipse.org "\
		rm -rf ${1}/* && \
		mkdir -p ${1} && \
		cp -r ${sourcepath} ${1} && \
		ln -sfn ${1} ${targetpath}latest"
```
Am I right?

> 
> 
> Otherwise this looks good.
> 
> Any update on restoring the old versions? I see the comment on gitlab that it is being restored from backup but so far nothing has appeared.

I have not yet heard anything either. But hope it will happen later today.

**Comment by kysmith-csg** [comment] 2023-10-26 17:04
> That is an interesting point. In general the semantic between both directory is like that. But if I understand you correctly instead of copying twice I would create a symlink from latest to the release I just copied. So the ssh part changes to:

It's a bit confusing for me because of the variable names and how it's being invoked. Basically,

1. Use `/gef/classic/latest` for nightly builds
2. If you are uploading release `3.18.0` for example,
    a. Put artifacts in `/gef/classic/releases/3.18.0`
    b. Link `/gef/classic/releases/latest` to `/gef/classic/releases/3.18.0` to signify that 3.18.0 is the latest official release
    c. When there is a new release, follow the same steps, linking `/releases/latest` to the newest folder to be uploaded (but keeping the old release where it is 😉 )

**Comment by azoitl** [comment] 2023-10-26 17:22
Ok this is roughly what we do. However I also need not only 3.18..0 but also 3.18.0M1, M2, M3, RC1

**Comment by azoitl** [comment] 2023-10-27 15:21
As the releases are now restored I spent today a bit of time to rework the promotion jobs. Based on your feedback, thx btw, I created now two build jobs: 

1. Promoting a milestone/RC build: https://ci.eclipse.org/gef/job/promote-gef-classic-milestone/
2. Promoting a release build: https://ci.eclipse.org/gef/job/promote-gef-classic/

The main difference between first and second is that the second will now update the latest release to link to the latest release. 

I also added checks that the inserted release number is correct and can not cause harm. I did some tests on my machine and in isolated state also on the Jenkins server. But I would love to get some feedback if I haven't missed anything. 

\cc @Phillipus @ptziegler  @vogella

**Comment by kysmith-csg** [comment] 2023-10-27 15:30
Not sure if this is normal or not, but I'm not actually able to see how these jobs are defined.

**Comment by azoitl** [comment] 2023-10-27 15:34
> Not sure if this is normal or not, but I'm not actually able to see how these jobs are defined.

I fear normal. Havent turned them into jenkins file based builds. I can post the scripts here if of interest.

**Comment by kysmith-csg** [comment] 2023-10-27 15:35
I thought you wanted us to check but if not then no problem ;) 

But regardless, you should check them in.

**Comment by azoitl** [comment] 2023-10-27 15:57
God point. I put it here because for I don't know how to do the Jenkins file stuff.

Release Promotion:
```
sourcepath="/home/data/httpd/download.eclipse.org/tools/gef/classic/latest/*"
targetpath="/home/data/httpd/download.eclipse.org/tools/gef/classic/releases/"
latestReleasePath=${targetpath}latest

#check release input param on validity 
if [[ $1 =~ ([0-9]+\.[0-9]+\.[0-9]+) ]]
then
	GEF_CLASSIC_VERSION="${BASH_REMATCH[1]}"	
else
	echo Wrong version format $1
	exit 1
fi

releasePath=${targetpath}${GEF_CLASSIC_VERSION}

echo Deploy GEF Classic Milestone Release to ${releasePath}

ssh genie.gef@projects-storage.eclipse.org /bin/sh  << EOF
  echo Deploy GEF Classic Milestone Release to ${releasePath}
  rm -rf ${releasePath}/* 
  mkdir -p ${releasePath} 
  cp -r ${sourcepath} ${releasePath}
  echo Create link for latest Release to ${latestReleasePath}
  rm -rf ${latestReleasePath}
  ln -s ${releasePath} ${latestReleasePath}
EOF
```

Milestone / RC promotion:
```
sourcepath="/home/data/httpd/download.eclipse.org/tools/gef/classic/latest/*"
targetpath="/home/data/httpd/download.eclipse.org/tools/gef/classic/releases/"

#check release input param on validity 
if [[ ${release} =~ ([0-9]+\.[0-9]+\.[0-9]+("RC"[12]|M[123])) ]]
then
	GEF_CLASSIC_VERSION="${BASH_REMATCH[1]}"	
else
	echo Wrong version format ${release}
	exit 1
fi

milestoneReleasePath=${targetpath}${GEF_CLASSIC_VERSION}

echo Deploy GEF Classic Milestone Release to ${milestoneReleasePath}

ssh genie.gef@projects-storage.eclipse.org /bin/sh  << EOF
  echo Deploy GEF Classic Milestone Release to ${milestoneReleasePath}
  rm -rf ${milestoneReleasePath}/*
  mkdir -p ${milestoneReleasePath}
  cp -r ${sourcepath} ${milestoneReleasePath}
EOF
```

**Comment by azoitl** [comment] 2023-11-15 17:49
I just performed the first Milestone release using the new infra. Everything went smooth. So I think it is fine to close this issue.

**Closed** 2023-11-16 14:40 UTC
